# Generated by Django 4.1.3 on 2022-11-07 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gmonit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ф.И.О.")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("EN", "Инженер"),
                            ("E1", "Инженер 1 катогории"),
                            ("E2", "Инженер 2 категории"),
                            ("LE", "Ведущий инженер"),
                            ("BS", "Начальник отдела"),
                            ("HR", "Специалист отдела кадров"),
                            ("BH", "Специалист бухгалтерии"),
                        ],
                        max_length=2,
                        verbose_name="Должность",
                    ),
                ),
                ("email", models.CharField(max_length=255, verbose_name="E-mail")),
                ("telephone", models.CharField(max_length=255, verbose_name="Телефон")),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.AlterField(
            model_name="report",
            name="camera",
            field=models.CharField(max_length=200, verbose_name="Название камеры"),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="mine",
            field=models.CharField(max_length=200, verbose_name="Название шахты"),
        ),
        migrations.AlterField(
            model_name="report",
            name="num_crack_blocks",
            field=models.IntegerField(
                verbose_name="Кол-во полностью разрушенных целиков"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="num_destroy_blocks",
            field=models.IntegerField(
                verbose_name="Кол-во частично разрушенных целиков"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="text",
            field=models.TextField(verbose_name="Текст отчета"),
        ),
        migrations.AlterField(
            model_name="report",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название отчета"),
        ),
        migrations.AlterField(
            model_name="report",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gmonit.author",
                verbose_name="Автор",
            ),
        ),
    ]
