# Generated by Django 4.1.3 on 2022-11-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmonit", "0003_alter_report_author"),
    ]

    operations = [
        migrations.RenameModel(old_name="Author", new_name="Worker",),
    ]
