# Generated by Django 4.0.5 on 2022-11-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmonit', '0004_rename_author_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gmonit.worker', verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gmonit.mine')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='camera',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='gmonit.camera', verbose_name='Название камеры'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mine',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='gmonit.mine', verbose_name='Название шахты'),
        ),
    ]
