# Generated by Django 4.0.5 on 2022-11-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmonit', '0005_mine_alter_report_author_camera_alter_report_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gmonit.mine', to_field='name'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
