# Generated by Django 4.0.5 on 2022-11-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmonit', '0006_alter_camera_mine_alter_mine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gmonit.mine'),
        ),
    ]
